#!/usr/bin/env bash
set -euo pipefail

# Print the current song as JSON, as reported by playerctl, every interval for
# display in waybar
SLEEP_INTERVAL=5
# We only care about what Spotify is playing
PLAYERCTL_ARGS='--player spotify'

# Replace ampersands with their HTML entity &amp;
function sanitise {
  echo "$1" | sed -r 's/&/&amp;/'
}

playerctl_cmd="playerctl $PLAYERCTL_ARGS"
while [ 1 ]; do
  if [ "$($playerctl_cmd status)" = "Playing" ]; then
    title="$($playerctl_cmd metadata title)"
    album="$($playerctl_cmd metadata album)"
    artist="$($playerctl_cmd metadata artist)"
    echo -n '{'
    echo -n '"text": "'$(sanitise "${title} - ${artist}")'", '
    echo -n '"tooltip": "'"Title: ${title}\nAlbum: ${album}\nArtist: ${artist}"'", '
    echo -n '"class": ""'
    echo '}'
  else
    echo
  fi
  sleep $SLEEP_INTERVAL
done
