name: "Test Home Manager configuration."
on: [push]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Nix formatting
      run: nix fmt -- --ci

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Install home-manager and realise home.nix
      run: |
        # Create profile folders home-manager expects to exist.
        nix profile list
        # Move the nix.conf file created by magic-nix-cache rather than fail.
        nix run home-manager/master -- switch --flake .#apearwin-ci -b backup
