name: "Test Home Manager configuration."
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Install home-manager and realise home.nix
      run: nix run home-manager/master -- switch --flake .#apearwin
